image: node:latest

cache:
  paths:
  - node_modules/

stages:  
  - build

build_docker:
  image: docker:latest
  stage: build
  only:
    - master
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:latest" .
    - docker export --output="imageFileUpload.tar" "$CI_REGISTRY_IMAGE:latest"
  artifacts:
    name: 'docker_FU_image.tar'
    when: on_success
    paths:
      - imageFileUpload.tar


